#서버 설정
server:
  port: 8085

# thymeleaf 설정
spring:
  thymeleaf:
    enabled: true
    prefix: classpath:/templates/thymeleaf/
    suffix: .html
    cache: false
    
  #devtools 설정
  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true
  freemarker:
    cache: false
    
    
#DB 설정
  datasource:
    url: jdbc:mysql://localhost/strchingDB?characterEncoding=UTF-8&serverTimezone=Asia/Seoul
    username: strchingadmin
    password: tmxmfpcld1!
    driver-class-name: com.mysql.cj.jdbc.Driver
    
  web:
    resources:
      static-locations:
        -classpath:/static/
        -file:./json/
        

